### ISSUE TITLE
Umzug zu FOR

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/yuploader#19]
ich würde den aktuellen Stand jetzt gerne an FOR abgeben und hoffen, dass sich doch noch jemand daran beteiligt.

Das Addon hat jetzt einen prinzipiell funktionstüchtigen Zustand, auch wenn es noch nicht die Qualität hat, die ich mir gewünscht habe.

**Comment by skerbis** [comment]
done
